metadata:
  default_version: "6.4.1"

versions:
  "6.4.1":
    ubuntu:
      "22.04":
        codename: "jammy"
        python_version: "cp310"
        rocm:
          driver_url: "https://repo.radeon.com/amdgpu-install/6.4.1/ubuntu/jammy/amdgpu-install_6.4.60401-1_all.deb"
          wsl:
            driver_url: "https://repo.radeon.com/amdgpu-install/6.4.1/ubuntu/jammy/amdgpu-install_6.4.60401-1_all.deb"
            install_command: "amdgpu-install -y --usecase=wsl,rocm --no-dkms"
        pytorch:
          wheel_urls:
            torch: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/torch-2.6.0%2Brocm6.4.1.git1ded221d-cp310-cp310-linux_x86_64.whl"
            torchvision: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/torchvision-0.21.0%2Brocm6.4.1.git4040d51f-cp310-cp310-linux_x86_64.whl"
            triton: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/pytorch_triton_rocm-3.2.0%2Brocm6.4.1.git6da9e660-cp310-cp310-linux_x86_64.whl"
            torchaudio: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/torchaudio-2.6.0%2Brocm6.4.1.gitd8831425-cp310-cp310-linux_x86_64.whl"
        tensorflow:
          wheel_url: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/tensorflow_rocm-2.18.1-cp310-cp310-manylinux_2_28_x86_64.whl"
        onnxruntime:
          repo_url: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/"
      "24.04":
        codename: "noble"
        python_version: "cp312"
        rocm:
          driver_url: "https://repo.radeon.com/amdgpu-install/6.4.1/ubuntu/noble/amdgpu-install_6.4.60401-1_all.deb"
          wsl:
            driver_url: "https://repo.radeon.com/amdgpu-install/6.4.1/ubuntu/noble/amdgpu-install_6.4.60401-1_all.deb"
            install_command: "amdgpu-install -y --usecase=wsl,rocm --no-dkms"
        pytorch:
          wheel_urls:
            torch: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/torch-2.6.0%2Brocm6.4.1.git1ded221d-cp312-cp312-linux_x86_64.whl"
            torchvision: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/torchvision-0.21.0%2Brocm6.4.1.git4040d51f-cp312-cp312-linux_x86_64.whl"
            triton: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/pytorch_triton_rocm-3.2.0%2Brocm6.4.1.git6da9e660-cp312-cp312-linux_x86_64.whl"
            torchaudio: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/torchaudio-2.6.0%2Brocm6.4.1.gitd8831425-cp312-cp312-linux_x86_64.whl"
        tensorflow:
          wheel_url: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/tensorflow_rocm-2.18.1-cp312-cp312-manylinux_2_28_x86_64.whl"
        onnxruntime:
          repo_url: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/"
  "6.3.4":
    ubuntu:
      "22.04":
        codename: "jammy"
        python_version: "cp310"
        rocm:
          driver_url: "https://repo.radeon.com/amdgpu-install/6.3.4/ubuntu/jammy/amdgpu-install_6.3.60304-1_all.deb"
          wsl:
            driver_url: "https://repo.radeon.com/amdgpu-install/6.3.4/ubuntu/jammy/amdgpu-install_6.3.60304-1_all.deb"
            install_command: "amdgpu-install -y --usecase=wsl,rocm --no-dkms"
        pytorch:
          wheel_urls:
            torch: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.4/torch-2.4.0%2Brocm6.3.4.git7cecbf6d-cp310-cp310-linux_x86_64.whl"
            torchvision: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.4/torchvision-0.19.0%2Brocm6.3.4.gitfab84886-cp310-cp310-linux_x86_64.whl"
            triton: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.4/pytorch_triton_rocm-3.0.0%2Brocm6.3.4.git75cc27c2-cp310-cp310-linux_x86_64.whl"
            torchaudio: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.4/torchaudio-2.4.0%2Brocm6.3.4.git69d40773-cp310-cp310-linux_x86_64.whl"
        tensorflow:
          wheel_url: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.4/tensorflow_rocm-2.17.0-cp310-cp310-manylinux_2_28_x86_64.whl"
        onnxruntime:
          repo_url: "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.4/" 